POST http://localhost:8081/register
Content-Type: application/json

{
    firstname : 'Vinno',
    lastname : 'Yunior',
    email : 'mypgaming99@gmail.com',
    password : 'Vinno260510'
}

###
POST  http://localhost:8081/login
Content-Type: application/json

{
    email : 'myanpetra99@gmail.com',
    password : 'Vinno2605'
}
